---
- name: Install Passbolt
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Installations
      block:
        - name: Actualizar caché de apt
          apt:
            update_cache: true
        - name: Basic Packages
          apt:
            name:
              - software-properties-common
              - gnupg
            state: present
        - name: Add PHP Repo
          apt_repository:
            repo: ppa:ondrej/php
            state: present
        - name: Add GPG Tailscale key
          apt_key:
            url: https://pkgs.tailscale.com/stable/ubuntu/noarmor.gpg
            state: present
        - name: Add Tailscale repo
          apt_repository:
            repo: "deb https://pkgs.tailscale.com/stable/ubuntu {{ ansible_lsb.codename }} main"
            state: present
        - name: Update apt cache
          apt:
            update_cache: true
      become: true

    - name: Install nginx, MySQL, PHP >= 8.2
      apt:
        name:
          - nginx
          - mysql-server
          - php8.2
          - php8.2-fpm
          - php8.2-cli
          - composer
          - git
          - gnupg
          - tailscale
          # Extensiones PHP adicionales
          - php8.2-gnupg
          - php8.2-intl
          - php8.2-mbstring
          - php8.2-xml
          - php8.2-gd
          - php8.2-imagick
          - php8.2-mysql
          - php8.2-curl
          - php8.2-ldap
        state: present
        update_cache: true
      become: true
