---
- name: Install Passbolt
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  tasks:
    - name: Installations
      block:
        - name: Update APT cache
          apt:
            update_cache: true
        - name: Basic Packages
          apt:
            name:
              - software-properties-common
              - gnupg
              - curl
            state: present
        - name: Download Passbolt repository setup script
          command: curl -LO https://download.passbolt.com/ce/installer/passbolt-repo-setup.ce.sh
          args:
            chdir: /tmp
        - name: Download Tailscale GPG key (modern method)
          get_url:
            url: "https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_lsb.codename }}.noarmor.gpg"
            dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
            mode: "0644"
        - name: Download Tailscale apt source list
          get_url:
            url: "https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_lsb.codename }}.tailscale-keyring.list"
            dest: /etc/apt/sources.list.d/tailscale.list
            mode: "0644"
        - name: Update apt cache
          apt:
            update_cache: true
        - name: Install Tailscale
          apt:
            name:
              - tailscale
            state: present
            update_cache: true

    - name: Run passbolt setup
      block:
        - name: Run Passbolt repo setup script
          shell: sudo bash ./passbolt-repo-setup.ce.sh
          args:
            chdir: /tmp
